### ISSUE TITLE
Instant Testing After Curation Update

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#349] opened 2022-01-04 18:52 UTC
**Website request** (CGWM-44) - ClinGen Website JIRA Board [ticket link](https://broadinstitute.atlassian.net/jira/software/projects/CGWM/boards/766?assignee=5b64af2ef220fc2d9cb5f3de&selectedIssue=CGWM-44)

**Description**
The website should incorporate a series of health check testing after a curation has been released from the site.  The current site is plagued by issues when a curation is released to the site by the current database doesn’t have record of one of the identifiers.  Typically we find out there is an issue after curator or user contacts us directly.

After a curation has been processed by the site the site should go through a series of front-end testing to confirm that the curation knowledge that was sent has source code included as expected.

**Comment by KelseaChang5** [comment] 2022-01-06 13:14
@tnavatar Can you please provide an estimate on an expected date of completion for this? Thanks!

**Comment by tnavatar** [comment] 2022-01-06 13:33
Right now this is unscheduled; I have no estimate for completion.

**Comment by tnavatar** [comment] 2022-01-06 19:23
* Overview

  Occasionally a published curation does not show up on the ClinGen website, or it shows up with incomplete or incorrect data. Right now these generally just get left on the floor (or published as-is), with no notification. If the curator doesn't check to make sure their curation found its way on the website it could be a while before anyone realizes there is a problem. This is far from ideal, but since curations generally show up on the website immediately after publication, it has worked (mostly). Curators are generally in the habit of checking their work on the website immediately after pubilcation (the GCI even provides a link to the anticipated URL). A proper technical solution is at least a little bit complicated, since the curation transits a few different platforms before it gets to the website. Here we try to scope out what a minimum useful solution would look like and get a sense of what the impact would be.
  
* Impact to workstreams

  There are three different workstreams we're concerned with, that each have three different curation platforms. Each have had failure to publish, either dropping an entire curation or a portion thereof, but the reasons differ by tool.
  
** Gene Validity

   These have generally been reliable. The GCI requires coded values and (I think) validates input requiring a coded vocabulary against the source. I'll have to work to recall specific examples, but failures to publish have generally been due to missunderstandings on expected input/output, or programming errors (on both sides).
   
** Gene Dosage

   These have probably been the most problematic.  Rather than having an explicit publication workflow, a microservice publishes any observed changes in JIRA with a five-minute polling interval. Genegraph decides whether to publish a curation by the ticket status in JIRA (only tickets that are 'closed' and 'complete' get published). The DCI performs no validation for input formats or controlled vocabularies, (i.e. MONDO identifier). 
   
** Actionability

   Problems have almost exclusively been due to programming errors in the ACI, which has at times even produced invalid JSON. This will generally result in no curations being published until the error is corrected by the ACI team. 
   
* Design overview

  The end goal would be for any issue to be reported back to the responsible party. The problem is that the repsonsible party will not generally be clear to Genegraph (did the curator make a mistake? did the curation interface have a bug, or pass through invalid input?). Moreover, Genegraph is just one piece of an increasingly complicated architecture; both the input and the output to end users fall outside the responsibilities of the Genegraph team.

** Architecture

   We assert a few architectual principles regarding Genegraph's role in this system:
  
*** Genegraph is responsible for validating its input data

    Ultimately, the decision to use data is made by the consumer of the data; we'll improve our ability to test input data for correctness.
    
*** The curation interface is responsible for producing correct output

    The whole point of this is to deal with the case where the curation interface either fails to do so, or Genegraph fails to process correct output appropriately, or a disagreement as to what constitutes correct output is revealed.

*** It is Genegraph's responsibility to report validation failures to Genegraph developers, the curation inteface (and its developers)

    The issue is not that Genegraph performs no validation (it does, not enough, but some). The issue is that there is no mechanism to report a validation failure when it occurs, apart from the end user noticing and saying something.

*** Notifications should occur via a Kafka topic
    
*** It is not Genegraph's responsibility to report validation failures to users.

    Most of the time it's a programmer's error anyway.

*** We may still want to consider publishing reports to a public slack channel

**Comment by tnavatar** [comment] 2022-01-20 14:54
I think we defined the scope of this ticket as planning, but not implementation--which is probably an epic-level discussion. Moving to Review given the above plan.

**Closed** 2022-03-14 20:07 UTC
Labels: website request, quality
