### ISSUE TITLE
Long delays in displaying the Gene-Disease Validity Listing

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/genegraph#600] opened 2022-06-27 19:57 UTC
(https://broadinstitute.atlassian.net/browse/CGWM-392)

More and more often, it appears that genegraph is losing its cache for the Gene-Disease Validity listing.  This causes the return from genegraph to take over a minute.  In the past, this almost never happened during prime business hours, but now it seems to.  For example, a quick visit to the page at 10:20AM took over a minute to respond.

I don’t know if there is anything that can be done, and it’s been mentioned in the past so there may already be a genegraph ticket open.  This ticket on the web side is being opened so we it doesn’t get forgotten.

The end-user experience is that it appears the website is unresponsive for about a minute when viewing the GDV listing page.  Today, this has happened almost every time I’ve visited the page, including simply refreshing the page.  That would indicate that it might be a deeper issue.

**Comment by tnavatar** [comment] 2022-06-29 11:56
Based on an analysis of the most recent 350 requests with this query, we find the vast majority of queries return in ~150ms, well within a reasonable response time for a query of this size. That being said, there are 10 responses over 2 seconds, with two responses taking nearly 20 seconds to return. We would like to understand the cause of these outliers, as this exceeds the time we would hope to see a response to this query. Right now our logging system does not capture enough data for us to get a clear sense of what might be causing these outliers.  We intend to add parameters to this that could point at the underlying issue and continue to monitor the performance of this (and other) queries.

**Comment by tnavatar** [comment] 2022-07-18 13:01
Per conversation on Thursday call, this problem does not seem to be causing any acute distress, and response times are generally in line with expectations. This is still work we want to do, but may take a lower priority relative to other issues on our plate. Moving to backlog for the time being.

**Comment by toneillbroad** [comment] 2022-09-28 00:28
genegraph-gvdev is configured with ":genegraph-gql-cache false" so this may have some effect, though I would think the response cache is more in play. Either way, we should re-enable the gql cache.

**Comment by toneillbroad** [comment] 2022-10-05 19:54
I'm going to reconfigure the gvdev test environment ahead of testing to enable ":genegraph-gql-cache true"

**Closed** 2022-10-20 16:27 UTC
Labels: bug, genevalidity, website request
